USE master;
GO

IF DB_ID('BD_SALUDCONNECT') IS NOT NULL
BEGIN
    ALTER DATABASE BD_SALUDCONNECT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BD_SALUDCONNECT;
END
GO

CREATE DATABASE BD_SALUDCONNECT;
GO

USE BD_SALUDCONNECT;
GO

CREATE TABLE TB_RELATIONSHIP(
    ID_RELATIONSHIP INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPTION_RELATIONSHIP VARCHAR(20)
);
GO

CREATE TABLE TB_EMERGENCY_CONTACT(
    ID_E_CONTACT INT PRIMARY KEY IDENTITY (1,1),
    NAMES_CONTACT VARCHAR(50) NULL,
    LAST_NAME_PAT VARCHAR(50) NULL,
    LAST_NAME_MAT VARCHAR(50) NULL,
    ID_RELATIONSHIP INT,
    PHONE_EMERGENCY VARCHAR(9) NULL,
    FOREIGN KEY (ID_RELATIONSHIP) REFERENCES TB_RELATIONSHIP(ID_RELATIONSHIP)
);
GO

CREATE TABLE TB_ROLES (
    ID_ROLE INT PRIMARY KEY IDENTITY(1,1),
    NAME_ROLE VARCHAR(20) NOT NULL,
    FLG_DELETE BIT DEFAULT 0
);
GO

CREATE TABLE TB_SPECIALTIES (
    ID_SPECIALTY INT PRIMARY KEY IDENTITY(1,1),
    NAME_SPECIALTY VARCHAR(50) NOT NULL,
    DESCRIPTION_SPECIALITY VARCHAR(150) NOT NULL,
    FLG_DELETE BIT DEFAULT 0
);
GO

CREATE TABLE TB_CONSULTORIES (
    ID_CONSULTORIES INT PRIMARY KEY IDENTITY(1,1),
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    NUMBER_CONSULTORIES VARCHAR(10) NOT NULL UNIQUE,
    FLOOR_NUMBER INT NOT NULL
);
GO

CREATE TABLE TB_USERS (
    ID_USER INT PRIMARY KEY IDENTITY(1,1),
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME_PAT VARCHAR(50) NOT NULL,
    LAST_NAME_MAT VARCHAR(50) NOT NULL,
    DOCUMENT VARCHAR(9) NOT NULL UNIQUE,
    BIRTHDATE DATE NOT NULL,
    PHONE VARCHAR(13) NOT NULL,
    GENDER CHAR(1) NOT NULL CHECK (GENDER IN ('M','F')),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ID_ROLE INT NOT NULL REFERENCES TB_ROLES(ID_ROLE),
    ID_E_CONTACT INT,
    DATE_REGISTER DATETIME NOT NULL DEFAULT GETDATE(),
    PROFILE_PICTURE VARCHAR(MAX) NULL,              
    FLG_DELETE BIT DEFAULT 0,
    FOREIGN KEY (ID_E_CONTACT) REFERENCES TB_EMERGENCY_CONTACT(ID_E_CONTACT)
);
GO

CREATE TABLE TB_DOCTOR_SPECIALTIES (
    ID_DOCTOR INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    YEARS_EXPERIENCE INT DEFAULT 0,
    EXPERIENCE VARCHAR(120) NOT NULL,
    DOC_LANGUAGES VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_DOCTOR, ID_SPECIALTY)
);
GO

CREATE TABLE TB_DOCTOR_SCHEDULES (
    ID_SCHEDULE INT PRIMARY KEY IDENTITY(1,1),
    ID_DOCTOR INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_CONSULTORIES INT NOT NULL REFERENCES TB_CONSULTORIES(ID_CONSULTORIES),
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,     
    DURACION_CITA INT NOT NULL DEFAULT 20,
    UNIQUE (ID_DOCTOR, FECHA_INICIO)
);
GO

CREATE TABLE TB_APPOINTMENTS (
    ID_APPOINTMENT INT PRIMARY KEY IDENTITY(1,1),
    ID_PATIENT INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_DOCTOR INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    DATE_APPOINTMENT DATETIME NOT NULL,
    ID_CONSULTORIES INT NOT NULL REFERENCES TB_CONSULTORIES(ID_CONSULTORIES),
    STATE CHAR(1) NOT NULL CHECK (STATE IN ('A','P','X','N')),
    APPOINTMENT_PRICE DECIMAL(10,2) NOT NULL DEFAULT 20.00
);
GO

CREATE TABLE TB_SERVICES (
    ID_SERVICE INT PRIMARY KEY IDENTITY(1,1),
    NAME_SERVICE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    DURATION_MINUTES INT NOT NULL,
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    FLG_DELETE BIT DEFAULT 0
);
GO

CREATE TABLE TB_MEDICAL_RECORDS (
    ID_RECORD INT PRIMARY KEY IDENTITY(1,1),
    ID_APPOINTMENT INT NOT NULL UNIQUE REFERENCES TB_APPOINTMENTS(ID_APPOINTMENT),
    DATE_REPORT DATETIME NOT NULL DEFAULT GETDATE(),
    OBSERVATIONS VARCHAR(2000) NOT NULL,
    DIAGNOSIS VARCHAR(500) NULL,
    TREATMENT VARCHAR(2000) NOT NULL,
    FOLLOW_UP_DATE DATE NULL
);
GO

CREATE TABLE TB_ADDITIONAL_SERVICES (
    ID_ADD_SERVICE INT PRIMARY KEY IDENTITY(1,1),
    ID_RECORD INT NOT NULL REFERENCES TB_MEDICAL_RECORDS(ID_RECORD),
    ID_SERVICE INT NOT NULL REFERENCES TB_SERVICES(ID_SERVICE),
    PRICE_AT_TIME DECIMAL(10,2) NOT NULL,
    STATE CHAR(1) NOT NULL DEFAULT 'P' CHECK (STATE IN ('P', 'A', 'X')),
    UNIQUE (ID_RECORD, ID_SERVICE)
);
GO

PRINT 'Base de datos BD_SALUDCONNECT creada exitosamente.';
GO