USE master;
GO

IF DB_ID('BD_SALUDCONNECT') IS NOT NULL
BEGIN
    ALTER DATABASE BD_SALUDCONNECT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BD_SALUDCONNECT;
END
GO

CREATE DATABASE BD_SALUDCONNECT;
GO

USE BD_SALUDCONNECT;
GO

CREATE TABLE TB_RELATIONSHIP(
	ID_RELATIONSHIP INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPTION_RELATIONSHIP VARCHAR(20)
);
GO

INSERT INTO TB_RELATIONSHIP (DESCRIPTION_RELATIONSHIP) VALUES
('Esposo(a)'),
('Conviviente'),
('Hermano(a)'),
('Tio(a)'),
('Familiar');
GO

CREATE TABLE TB_EMERGENCY_CONTACT(
	ID_E_CONTACT INT PRIMARY KEY IDENTITY (1,1),
	NAMES_CONTACT VARCHAR(50) NULL,
	LAST_NAME_PAT VARCHAR(50) NULL,
    LAST_NAME_MAT VARCHAR(50) NULL,
	ID_RELATIONSHIP INT,
	PHONE_EMERGENCY VARCHAR(9) NULL,
	FOREIGN KEY (ID_RELATIONSHIP) REFERENCES TB_RELATIONSHIP(ID_RELATIONSHIP)
);
GO

INSERT INTO TB_EMERGENCY_CONTACT (NAMES_CONTACT,LAST_NAME_PAT,LAST_NAME_MAT,ID_RELATIONSHIP,PHONE_EMERGENCY) VALUES
('Juan Miguel','Casas','Villanueva',1,'928878787'),
('Sin Contacto','','',5,'');                    
GO

CREATE TABLE TB_ROLES (
    ID_ROLE INT PRIMARY KEY IDENTITY(1,1),
    NAME_ROLE VARCHAR(20) NOT NULL,
    FLG_DELETE BIT DEFAULT 0
);
GO

INSERT INTO TB_ROLES (NAME_ROLE) VALUES
('Paciente'),
('Administrador'),
('Doctor');
GO

CREATE TABLE TB_SPECIALTIES (
    ID_SPECIALTY INT PRIMARY KEY IDENTITY(1,1),
    NAME_SPECIALTY VARCHAR(50) NOT NULL,
    FLG_DELETE BIT DEFAULT 0
);
GO

INSERT INTO TB_SPECIALTIES (NAME_SPECIALTY) VALUES
('Cardiología'),
('Dermatología'),
('Neurología'),
('Pediatría'),
('Ortopedía'),
('Oftalmología'),
('Psiquiatría'),
('Medicina Interna');
GO

CREATE TABLE TB_CONSULTORIES (
    ID_CONSULTORIES INT PRIMARY KEY IDENTITY(1,1),
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    NUMBER_CONSULTORIES VARCHAR(10) NOT NULL UNIQUE,
    FLOOR_NUMBER INT NOT NULL
);
GO

INSERT INTO TB_CONSULTORIES (ID_SPECIALTY, NUMBER_CONSULTORIES, FLOOR_NUMBER) VALUES
(1, 'C-301', 3),
(1, 'C-302', 3),
(2, 'D-101', 1),
(2, 'D-102', 1),
(8, 'M-305', 3);
GO

CREATE TABLE TB_USERS (
    ID_USER INT PRIMARY KEY IDENTITY(1,1),
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME_PAT VARCHAR(50) NOT NULL,
    LAST_NAME_MAT VARCHAR(50) NOT NULL,
    DOCUMENT VARCHAR(9) NOT NULL UNIQUE,
	BIRTHDATE DATE NOT NULL,
	PHONE VARCHAR(13) NOT NULL,
	GENDER CHAR(1) NOT NULL CHECK (GENDER IN ('M','F')),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ID_ROLE INT NOT NULL REFERENCES TB_ROLES(ID_ROLE),
	ID_E_CONTACT INT,
    DATE_REGISTER DATETIME NOT NULL DEFAULT GETDATE(),
    PROFILE_PICTURE VARCHAR(200) NULL,              
    FLG_DELETE BIT DEFAULT 0,
	FOREIGN KEY (ID_E_CONTACT) REFERENCES TB_EMERGENCY_CONTACT(ID_E_CONTACT)
);
GO

SET DATEFORMAT DMY;
GO

INSERT INTO TB_USERS (FIRST_NAME, LAST_NAME_PAT, LAST_NAME_MAT, DOCUMENT, BIRTHDATE, PHONE, GENDER, EMAIL, PASSWORD_HASH, ID_ROLE, ID_E_CONTACT, DATE_REGISTER, PROFILE_PICTURE)
VALUES
('Admin', 'Principal', 'Uno', '123456723', '10/05/1990', '912345890', 'M', 'admin@example.com', 'clave123', 2, 2, '10/10/2024 10:00:00', NULL),
('Juan', 'Pérez', 'González', '123456789', '10/05/1990', '923457890', 'M', 'juan.perez@example.com', 'clave123', 1, 1, '15/01/2025 14:30:00', NULL),
('María', 'López', 'Hernández', '987654321', '25/08/1985', '987654322', 'F', 'maria.lopez@example.com', 'clave123', 3, 2, '01/12/2024 08:00:00', NULL),
('Carlos', 'Ramírez', 'Sánchez', '456789123', '15/12/1992', '987654323', 'M', 'carlos.ramirez@example.com', 'clave123', 3, 2, '05/12/2024 09:15:00', NULL),
('Ana', 'García', 'Díaz', '111222333', '01/01/2000', '900111222', 'F', 'ana.garcia@example.com', 'clave123', 1, 2, '20/02/2025 17:00:00', NULL);
GO

CREATE TABLE TB_DOCTOR_SPECIALTIES (
    ID_DOCTOR INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    YEARS_EXPERIENCE INT DEFAULT 0,
    PRIMARY KEY (ID_DOCTOR, ID_SPECIALTY)
);
GO

INSERT INTO TB_DOCTOR_SPECIALTIES (ID_DOCTOR, ID_SPECIALTY, YEARS_EXPERIENCE) VALUES
(3, 1, 10), 
(3, 8, 8),
(4, 2, 5);  
GO

CREATE TABLE TB_DOCTOR_SCHEDULES (
    ID_SCHEDULE INT PRIMARY KEY IDENTITY(1,1),
    ID_DOCTOR INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_CONSULTORIES INT NOT NULL REFERENCES TB_CONSULTORIES(ID_CONSULTORIES),
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,     
    DURACION_CITA INT NOT NULL DEFAULT 20,
    UNIQUE (ID_DOCTOR, FECHA_INICIO)
);
GO

INSERT INTO TB_DOCTOR_SCHEDULES (ID_DOCTOR, ID_CONSULTORIES, FECHA_INICIO, FECHA_FIN, DURACION_CITA) VALUES
(3, 1, '20/10/2025 08:00:00', '20/10/2025 13:00:00', 20), 
(4, 4, '21/10/2025 14:00:00', '21/10/2025 18:00:00', 20), 
(4, 3, '24/10/2025 10:00:00', '24/10/2025 16:00:00', 20); 
GO

CREATE TABLE TB_APPOINTMENTS (
    ID_APPOINTMENT INT PRIMARY KEY IDENTITY(1,1),
    ID_PATIENT INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_DOCTOR INT NOT NULL REFERENCES TB_USERS(ID_USER),
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    DATE_APPOINTMENT DATETIME NOT NULL,
    ID_CONSULTORIES INT NOT NULL REFERENCES TB_CONSULTORIES(ID_CONSULTORIES),
    STATE CHAR(1) NOT NULL CHECK (STATE IN ('A','P','X','N')),
    APPOINTMENT_PRICE DECIMAL(10,2) NOT NULL DEFAULT 20.00
);
GO

INSERT INTO TB_APPOINTMENTS (ID_PATIENT, ID_DOCTOR, ID_SPECIALTY, DATE_APPOINTMENT, STATE, APPOINTMENT_PRICE, ID_CONSULTORIES) VALUES
(2, 3, 1, '20/10/2025 08:00:00', 'A', 150.00, 1), 
(5, 4, 2, '21/10/2025 14:00:00', 'P', 120.00, 4), 
(2, 4, 2, '24/10/2025 10:20:00', 'X', 120.00, 3), 
(5, 3, 8, '20/10/2025 08:20:00', 'N', 140.00, 1); 
GO

CREATE TABLE TB_SERVICES (
    ID_SERVICE INT PRIMARY KEY IDENTITY(1,1),
    NAME_SERVICE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(500) NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    DURATION_MINUTES INT NOT NULL,
    ID_SPECIALTY INT NOT NULL REFERENCES TB_SPECIALTIES(ID_SPECIALTY),
    FLG_DELETE BIT DEFAULT 0
);
GO

INSERT INTO TB_SERVICES (NAME_SERVICE, DESCRIPTION, PRICE, DURATION_MINUTES, ID_SPECIALTY) VALUES
('Consulta Cardiología', 'Evaluación integral.', 150.00, 30, 1), 
('Electrocardiograma', 'Prueba diagnóstica.', 80.00, 15, 1),
('Consulta Dermatología', 'Diagnóstico de piel.', 120.00, 25, 2), 
('Biopsia de Piel', 'Toma de muestra.', 250.00, 45, 2), 
('Consulta Medicina Interna', 'Atención integral adultos.', 140.00, 30, 8), 
('Prueba de Glucosa en Ayunas', 'Análisis clínico.', 60.00, 20, 8);
GO

CREATE TABLE TB_MEDICAL_RECORDS (
    ID_RECORD INT PRIMARY KEY IDENTITY(1,1),
    ID_APPOINTMENT INT NOT NULL UNIQUE REFERENCES TB_APPOINTMENTS(ID_APPOINTMENT),
    DATE_REPORT DATETIME NOT NULL DEFAULT GETDATE(),
    OBSERVATIONS VARCHAR(2000) NOT NULL,
    DIAGNOSIS VARCHAR(500) NULL,
    TREATMENT VARCHAR(2000) NOT NULL,
    FOLLOW_UP_DATE DATE NULL
);
GO

INSERT INTO TB_MEDICAL_RECORDS (ID_APPOINTMENT, OBSERVATIONS, DIAGNOSIS, TREATMENT, FOLLOW_UP_DATE) VALUES
(1, 
 'Paciente refiere dolor torácico esporádico. TA: 135/85. Sin soplos.', 
 'Posible Angina Estable.', 
 'Indicar reposo y Aspirina 100mg/día. Se requieren exámenes adicionales.', 
 '03/11/2025' 
); 
GO

CREATE TABLE TB_ADDITIONAL_SERVICES (
    ID_ADD_SERVICE INT PRIMARY KEY IDENTITY(1,1),
    ID_RECORD INT NOT NULL REFERENCES TB_MEDICAL_RECORDS(ID_RECORD),
    ID_SERVICE INT NOT NULL REFERENCES TB_SERVICES(ID_SERVICE),
    PRICE_AT_TIME DECIMAL(10,2) NOT NULL,
    STATE CHAR(1) NOT NULL DEFAULT 'P' CHECK (STATE IN ('P', 'A', 'X')),
    UNIQUE (ID_RECORD, ID_SERVICE)
);
GO

INSERT INTO TB_ADDITIONAL_SERVICES (ID_RECORD, ID_SERVICE, PRICE_AT_TIME, STATE) VALUES
(1, 2, 80.00, 'P'),
(1, 6, 60.00, 'P');
GO



INSERT INTO TB_USERS (FIRST_NAME, LAST_NAME_PAT, LAST_NAME_MAT, DOCUMENT, BIRTHDATE, PHONE, GENDER, EMAIL, PASSWORD_HASH, ID_ROLE, ID_E_CONTACT, DATE_REGISTER, PROFILE_PICTURE)
VALUES
('', 'PacienteNuevo', 'PacienteNuevo', '98898989', '10/05/1990', '912345290', 'M', 'apacientenuevo@gmail.com', 'clave123', 1, 2, '10/10/2024 10:00:00', NULL);