-- ASEGURARSE DE ESTAR EN LA BASE DE DATOS CORRECTA
USE BD_SALUDCONNECT;
GO

/* ============================================
   PROCEDURES SESSION
   ============================================ */

IF OBJECT_ID('SP_LOGIN_USER', 'P') IS NOT NULL
    DROP PROCEDURE SP_LOGIN_USER;
GO

CREATE PROCEDURE SP_LOGIN_USER
    @EMAIL VARCHAR(100),
    @PASSWORD VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        U.ID_USER,
        U.FIRST_NAME,
        U.LAST_NAME_PAT,
        U.LAST_NAME_MAT,
        U.DOCUMENT,
        U.EMAIL,
        U.BIRTHDATE,
        U.GENDER,
        U.PHONE,
        U.ID_ROLE,
        R.NAME_ROLE
    FROM TB_USERS U
    INNER JOIN TB_ROLES R ON U.ID_ROLE = R.ID_ROLE
    WHERE U.EMAIL = @EMAIL AND U.PASSWORD_HASH = @PASSWORD AND U.FLG_DELETE = 0;

    IF EXISTS (
        SELECT 1
        FROM TB_USERS U
        WHERE U.EMAIL = @EMAIL AND U.PASSWORD_HASH = @PASSWORD AND U.FLG_DELETE = 0 AND U.ID_ROLE = 3
    )
    BEGIN
        SELECT 
            DS.ID_SPECIALTY,
            DS.YEARS_EXPERIENCE,
            S.NAME_SPECIALTY
        FROM TB_USERS U
        INNER JOIN TB_DOCTOR_SPECIALTIES DS ON U.ID_USER = DS.ID_DOCTOR
        INNER JOIN TB_SPECIALTIES S ON DS.ID_SPECIALTY = S.ID_SPECIALTY
        WHERE U.EMAIL = @EMAIL AND U.PASSWORD_HASH = @PASSWORD AND U.FLG_DELETE = 0;
    END
END
GO

IF OBJECT_ID('SP_REGISTER_PATIENTS', 'P') IS NOT NULL
    DROP PROCEDURE SP_REGISTER_PATIENTS;
GO

CREATE PROCEDURE SP_REGISTER_PATIENTS
    @FIRST_NAME VARCHAR(50),
    @LAST_NAME_PAT VARCHAR(50),
    @LAST_NAME_MAT VARCHAR(50),
    @DOCUMENT VARCHAR(9),
    @BIRTHDATE DATE,
    @PHONE VARCHAR(13),
    @GENDER CHAR(1),
    @EMAIL VARCHAR(100),
    @PASSWORD_HASH VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TB_USERS WHERE DOCUMENT = @DOCUMENT)
    BEGIN
        RAISERROR('El número de documento %s ya existe', 16, 1, @DOCUMENT);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM TB_USERS WHERE EMAIL = @EMAIL)
    BEGIN
        RAISERROR('El correo electrónico %s ya existe', 16, 1, @EMAIL);
        RETURN;
    END

    INSERT INTO TB_USERS(FIRST_NAME, LAST_NAME_PAT, LAST_NAME_MAT, DOCUMENT, BIRTHDATE, PHONE, GENDER, EMAIL, PASSWORD_HASH, ID_ROLE, ID_E_CONTACT)
    VALUES(@FIRST_NAME, @LAST_NAME_PAT, @LAST_NAME_MAT, @DOCUMENT, @BIRTHDATE, @PHONE, @GENDER, @EMAIL, @PASSWORD_HASH, 1, 2);

    SELECT SCOPE_IDENTITY() AS ID_USER;
END
GO

/* ============================================
   PROCEDURES SERVICES
   ============================================ */

IF OBJECT_ID('SP_LIST_SERVICES_FOR_DOCTOR', 'P') IS NOT NULL
    DROP PROCEDURE SP_LIST_SERVICES_FOR_DOCTOR;
GO

CREATE PROCEDURE SP_LIST_SERVICES_FOR_DOCTOR
    @IDDOCTOR INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        S.ID_SERVICE,
        S.NAME_SERVICE,
        S.DESCRIPTION,
        S.PRICE,
        S.DURATION_MINUTES, 
        SPE.ID_SPECIALTY, 
        SPE.NAME_SPECIALTY 
    FROM TB_SERVICES S
    INNER JOIN TB_SPECIALTIES SPE ON S.ID_SPECIALTY = SPE.ID_SPECIALTY
    INNER JOIN TB_DOCTOR_SPECIALTIES D ON D.ID_SPECIALTY = S.ID_SPECIALTY
    WHERE D.ID_DOCTOR = @IDDOCTOR AND S.FLG_DELETE = 0
    ORDER BY SPE.NAME_SPECIALTY, S.NAME_SERVICE;
END
GO

IF OBJECT_ID('SP_TOTAL_SERVICES', 'P') IS NOT NULL
    DROP PROCEDURE SP_TOTAL_SERVICES;
GO

CREATE PROCEDURE SP_TOTAL_SERVICES
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS totalServices
    FROM TB_SERVICES 
    WHERE FLG_DELETE = 0;
END
GO

IF OBJECT_ID('SP_MIN_SERVICE', 'P') IS NOT NULL
    DROP PROCEDURE SP_MIN_SERVICE;
GO

CREATE PROCEDURE SP_MIN_SERVICE
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MIN(DURATION_MINUTES) AS MinDuration
    FROM TB_SERVICES
    WHERE FLG_DELETE = 0;
END
GO

/* ============================================
   PROCEDURES APPOINTMENTS
   ============================================ */

IF OBJECT_ID('SP_APPOINTMENTS_TODAY_FOR_DOCTOR', 'P') IS NOT NULL
    DROP PROCEDURE SP_APPOINTMENTS_TODAY_FOR_DOCTOR;
GO

CREATE PROCEDURE SP_APPOINTMENTS_TODAY_FOR_DOCTOR
    @IDDOCTOR INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS AppointmentsToday
    FROM TB_APPOINTMENTS
    WHERE 
        ID_DOCTOR = @IDDOCTOR
        AND CAST(DATE_APPOINTMENT AS DATE) = CAST(GETDATE() AS DATE);
END
GO

IF OBJECT_ID('SP_TOTAL_PATIENTS_FOR_DOCTOR', 'P') IS NOT NULL
    DROP PROCEDURE SP_TOTAL_PATIENTS_FOR_DOCTOR;
GO

CREATE PROCEDURE SP_TOTAL_PATIENTS_FOR_DOCTOR
    @IDDOCTOR INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(DISTINCT ID_PATIENT) AS TotalUniquePatients
    FROM TB_APPOINTMENTS
    WHERE ID_DOCTOR = @IDDOCTOR;
END
GO

IF OBJECT_ID('SP_TOTAL_APPOINTMENTS_COMPLETED', 'P') IS NOT NULL
    DROP PROCEDURE SP_TOTAL_APPOINTMENTS_COMPLETED;
GO

CREATE PROCEDURE SP_TOTAL_APPOINTMENTS_COMPLETED
    @IDDOCTOR INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS CompletedAppointments
    FROM TB_APPOINTMENTS
    WHERE ID_DOCTOR = @IDDOCTOR AND STATE = 'A';
END
GO

IF OBJECT_ID('SP_COUNT_UPCOMMING_APPOINTMENTS_FOR_DOCTOR', 'P') IS NOT NULL
    DROP PROCEDURE SP_COUNT_UPCOMMING_APPOINTMENTS_FOR_DOCTOR;
GO

CREATE PROCEDURE SP_COUNT_UPCOMMING_APPOINTMENTS_FOR_DOCTOR
    @IDDOCTOR INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS UpcomingAppointments
    FROM TB_APPOINTMENTS
    WHERE 
        ID_DOCTOR = @IDDOCTOR 
        AND DATE_APPOINTMENT > GETDATE()
        AND STATE = 'P'; 
END
GO

IF OBJECT_ID('SP_LIST_APPOINTMENTS_BY_DATE_FOR_DOCTOR', 'P') IS NOT NULL
    DROP PROCEDURE SP_LIST_APPOINTMENTS_BY_DATE_FOR_DOCTOR;
GO

CREATE PROCEDURE SP_LIST_APPOINTMENTS_BY_DATE_FOR_DOCTOR
    @DoctorId INT,
    @Date DATE = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        A.ID_APPOINTMENT,
        P.ID_USER AS PatientId,
        P.FIRST_NAME,
        P.LAST_NAME_PAT,
        P.LAST_NAME_MAT,
        CAST(A.DATE_APPOINTMENT AS DATE) AS DateOnly,
        CONVERT(VARCHAR(5), A.DATE_APPOINTMENT, 108) AS AppointmentTime, 
        A.STATE,
        S.NAME_SPECIALTY,
        A.APPOINTMENT_PRICE
    FROM TB_APPOINTMENTS A
    INNER JOIN TB_USERS P ON A.ID_PATIENT = P.ID_USER
    INNER JOIN TB_SPECIALTIES S ON A.ID_SPECIALTY = S.ID_SPECIALTY
    WHERE A.ID_DOCTOR = @DoctorId
      AND (@Date IS NULL OR CAST(A.DATE_APPOINTMENT AS DATE) = @Date)
    ORDER BY A.DATE_APPOINTMENT;
END
GO

IF OBJECT_ID('SP_GET_APPOINTMENTS_FOR_7_DAYS', 'P') IS NOT NULL
    DROP PROCEDURE SP_GET_APPOINTMENTS_FOR_7_DAYS;
GO

CREATE PROCEDURE SP_GET_APPOINTMENTS_FOR_7_DAYS
    @DoctorId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        CAST(DATE_APPOINTMENT AS DATE) AS AppointmentDate,
        COUNT(*) AS TotalAppointments
    FROM TB_APPOINTMENTS
    WHERE 
        DATE_APPOINTMENT >= CAST(GETDATE() - 6 AS DATE) 
        AND DATE_APPOINTMENT < CAST(GETDATE() + 1 AS DATE) 
        AND STATE IN ('A', 'P', 'X', 'N')
        AND (@DoctorId IS NULL OR ID_DOCTOR = @DoctorId)
    GROUP BY 
        CAST(DATE_APPOINTMENT AS DATE)
    ORDER BY 
        AppointmentDate;
END
GO

IF OBJECT_ID('SP_GET_APPOINTEMNT_FOR_ID', 'P') IS NOT NULL
    DROP PROCEDURE SP_GET_APPOINTEMNT_FOR_ID;
GO

CREATE PROCEDURE SP_GET_APPOINTEMNT_FOR_ID
    @ID_APPOINTMENT INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        A.ID_APPOINTMENT,
        P.ID_USER AS PatientId,
        P.FIRST_NAME,
        P.LAST_NAME_PAT,
        P.LAST_NAME_MAT,
        P.DOCUMENT,
        P.BIRTHDATE,
        P.PHONE,
        P.GENDER,
        P.EMAIL,
        CAST(A.DATE_APPOINTMENT AS DATE) AS DateOnly,
        CONVERT(VARCHAR(5), A.DATE_APPOINTMENT, 108) AS AppointmentTime, 
        A.STATE,
        S.ID_SPECIALTY,
        S.NAME_SPECIALTY,
        A.APPOINTMENT_PRICE,
        C.NUMERO_CONSULTORIO,
        C.FLOOR_NUMBER,
        D.ID_USER AS DoctorId,
        D.FIRST_NAME AS DoctorFirstName,
        D.LAST_NAME_PAT AS DoctorLastNamePat,
        D.LAST_NAME_MAT AS DoctorLastNameMat
    FROM TB_APPOINTMENTS A
    INNER JOIN TB_USERS P ON A.ID_PATIENT = P.ID_USER
    INNER JOIN TB_USERS D ON A.ID_DOCTOR = D.ID_USER
    INNER JOIN TB_SPECIALTIES S ON A.ID_SPECIALTY = S.ID_SPECIALTY
    INNER JOIN TB_CONSULTORIOS C ON A.ID_CONSULTORIO = C.ID_CONSULTORIO
    WHERE A.ID_APPOINTMENT = @ID_APPOINTMENT;
END
GO

IF OBJECT_ID('SP_APPOINTMENT_CHANGE_STATE', 'P') IS NOT NULL
    DROP PROCEDURE SP_APPOINTMENT_CHANGE_STATE;
GO

CREATE PROCEDURE SP_APPOINTMENT_CHANGE_STATE
    @IDAPPOINTMENT INT,
    @STATE CHAR(1)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM TB_APPOINTMENTS WHERE ID_APPOINTMENT = @IDAPPOINTMENT)
    BEGIN
        RAISERROR('La cita con ID %d no existe', 16, 1, @IDAPPOINTMENT);
        RETURN;
    END

    IF @STATE NOT IN ('A', 'P', 'X', 'N')
    BEGIN
        RAISERROR('Estado inválido. Use: A=Atendido, P=Pendiente, X=Cancelado, N=No asistió', 16, 1);
        RETURN;
    END

    UPDATE TB_APPOINTMENTS
    SET STATE = @STATE
    WHERE ID_APPOINTMENT = @IDAPPOINTMENT;

    SELECT 'Estado actualizado exitosamente' AS Mensaje;
END
GO

/* ============================================
   PROCEDURES SPECIALTIES
   ============================================ */

IF OBJECT_ID('SP_TOTAL_SPECIALTIES', 'P') IS NOT NULL
    DROP PROCEDURE SP_TOTAL_SPECIALTIES;
GO

CREATE PROCEDURE SP_TOTAL_SPECIALTIES
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS totalSpecialties
    FROM TB_SPECIALTIES 
    WHERE FLG_DELETE = 0;
END
GO

/* ============================================
   PROCEDURES DOCTOR
   ============================================ */

IF OBJECT_ID('SP_TOTAL_DOCTOR', 'P') IS NOT NULL
    DROP PROCEDURE SP_TOTAL_DOCTOR;
GO

CREATE PROCEDURE SP_TOTAL_DOCTOR
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS totalDoctors
    FROM TB_USERS
    WHERE ID_ROLE = 3 AND FLG_DELETE = 0;
END
GO

/* ============================================
   PROCEDURES USER
   ============================================ */

IF OBJECT_ID('SP_GET_USER_PROFILE', 'P') IS NOT NULL
    DROP PROCEDURE SP_GET_USER_PROFILE;
GO

CREATE PROCEDURE SP_GET_USER_PROFILE
    @ID_USER INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        U.ID_USER,
        U.FIRST_NAME,
        U.LAST_NAME_PAT,
        U.LAST_NAME_MAT,
        U.DOCUMENT,
        U.BIRTHDATE,
        U.PHONE,
        U.GENDER,
        U.EMAIL,
        U.ID_ROLE,
        R.NAME_ROLE,
        U.PROFILE_PICTURE,
        U.DATE_REGISTER,
        EC.NAMES_CONTACT,
        EC.LAST_NAME_PAT AS EmergencyLastNamePat,
        EC.LAST_NAME_MAT AS EmergencyLastNameMat,
        EC.PHONE_EMERGENCY,
        REL.DESCRIPTION_RELATIONSHIP
    FROM TB_USERS U
    INNER JOIN TB_ROLES R ON U.ID_ROLE = R.ID_ROLE
    LEFT JOIN TB_EMERGENCY_CONTACT EC ON U.ID_E_CONTACT = EC.ID_E_CONTACT
    LEFT JOIN TB_RELATIONSHIP REL ON EC.ID_RELATIONSHIP = REL.ID_RELATIONSHIP
    WHERE U.ID_USER = @ID_USER AND U.FLG_DELETE = 0;

    IF EXISTS (SELECT 1 FROM TB_USERS WHERE ID_USER = @ID_USER AND ID_ROLE = 3 AND FLG_DELETE = 0)
    BEGIN
        SELECT 
            DS.ID_SPECIALTY,
            S.NAME_SPECIALTY,
            DS.YEARS_EXPERIENCE
        FROM TB_DOCTOR_SPECIALTIES DS
        INNER JOIN TB_SPECIALTIES S ON DS.ID_SPECIALTY = S.ID_SPECIALTY
        WHERE DS.ID_DOCTOR = @ID_USER;
    END
END
GO

/* ============================================
   PROCEDURES ADMIN
   ============================================ */

IF OBJECT_ID('SP_Total_Appointments', 'P') IS NOT NULL
    DROP PROCEDURE SP_Total_Appointments;
GO

CREATE PROCEDURE SP_Total_Appointments
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS TotalAppointments
    FROM TB_APPOINTMENTS;
END
GO

/* ============================================
   PROCEDURES PACIENTE-CLIENTE
   Estados: A=Atendido, P=Pendiente, X=Cancelado, N=No asistió
   ============================================ */

IF OBJECT_ID('sp_total_citas', 'P') IS NOT NULL
    DROP PROCEDURE sp_total_citas;
GO

CREATE PROCEDURE sp_total_citas
    @idPaciente INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS Total_Citas 
    FROM TB_APPOINTMENTS
    WHERE ID_PATIENT = @idPaciente;
END
GO

IF OBJECT_ID('sp_total_citas_asistidas', 'P') IS NOT NULL
    DROP PROCEDURE sp_total_citas_asistidas;
GO

CREATE PROCEDURE sp_total_citas_asistidas
    @idPaciente INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS Citas_Asistidas 
    FROM TB_APPOINTMENTS
    WHERE ID_PATIENT = @idPaciente AND STATE = 'A';
END
GO

IF OBJECT_ID('sp_total_citas_pendientes', 'P') IS NOT NULL
    DROP PROCEDURE sp_total_citas_pendientes;
GO

CREATE PROCEDURE sp_total_citas_pendientes
    @idPaciente INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS Citas_Pendientes 
    FROM TB_APPOINTMENTS
    WHERE ID_PATIENT = @idPaciente AND STATE = 'P';
END
GO

IF OBJECT_ID('sp_total_citas_canceladas', 'P') IS NOT NULL
    DROP PROCEDURE sp_total_citas_canceladas;
GO

CREATE PROCEDURE sp_total_citas_canceladas
    @idPaciente INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS Citas_Canceladas 
    FROM TB_APPOINTMENTS
    WHERE ID_PATIENT = @idPaciente AND STATE = 'X';
END
GO

IF OBJECT_ID('sp_proximas_citas', 'P') IS NOT NULL
    DROP PROCEDURE sp_proximas_citas;
GO

CREATE PROCEDURE sp_proximas_citas
    @idPaciente INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        a.ID_APPOINTMENT,
        CONCAT(d.FIRST_NAME, ' ', d.LAST_NAME_PAT, ' ', d.LAST_NAME_MAT) AS Nombres_Completos,
        s.NAME_SPECIALTY,
        FORMAT(a.DATE_APPOINTMENT, 'HH:mm') AS Hora_Cita,
        FORMAT(a.DATE_APPOINTMENT, 'dd/MM/yyyy') AS Fecha_Cita,
        a.STATE,
        a.APPOINTMENT_PRICE,
        c.NUMERO_CONSULTORIO,
        c.FLOOR_NUMBER
    FROM TB_APPOINTMENTS a
    INNER JOIN TB_USERS d ON a.ID_DOCTOR = d.ID_USER
    INNER JOIN TB_SPECIALTIES s ON a.ID_SPECIALTY = s.ID_SPECIALTY
    INNER JOIN TB_CONSULTORIOS c ON a.ID_CONSULTORIO = c.ID_CONSULTORIO
    WHERE a.ID_PATIENT = @idPaciente 
        AND a.DATE_APPOINTMENT >= CAST(GETDATE() AS DATE)
        AND a.STATE = 'P'
    ORDER BY a.DATE_APPOINTMENT ASC;
END
GO

IF OBJECT_ID('sp_total_doctores', 'P') IS NOT NULL
    DROP PROCEDURE sp_total_doctores;
GO

CREATE PROCEDURE sp_total_doctores
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS total_Doctores 
    FROM TB_USERS 
    WHERE ID_ROLE = 3 AND FLG_DELETE = 0;
END
GO

/* ============================================
   PROCEDURES SCHEDULES
   ============================================ */

IF OBJECT_ID('SP_CALCULAR_CAPACIDAD_SEGUN_HORARIO', 'P') IS NOT NULL
    DROP PROCEDURE SP_CALCULAR_CAPACIDAD_SEGUN_HORARIO;
GO

CREATE PROCEDURE SP_CALCULAR_CAPACIDAD_SEGUN_HORARIO
    @ScheduleID INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @StartTime DATETIME;
    DECLARE @EndTime DATETIME;
    DECLARE @SlotDuration INT;
    DECLARE @TotalMinutes DECIMAL(10, 2);
    DECLARE @MaxCapacity INT;

    SELECT
        @StartTime = FECHA_INICIO,
        @EndTime = FECHA_FIN,
        @SlotDuration = DURACION_CITA
    FROM TB_DOCTOR_SCHEDULES
    WHERE ID_SCHEDULE = @ScheduleID;

    IF @StartTime IS NULL
    BEGIN
        SELECT 
            0 AS MaxCapacity, 
            0 AS TotalMinutesInShift,
            0 AS SlotDurationMinutes,
            'Error: Horario no encontrado.' AS StatusMessage;
        RETURN;
    END

    SET @TotalMinutes = DATEDIFF(MINUTE, @StartTime, @EndTime);

    IF @SlotDuration <= 0
    BEGIN
        SELECT 
            0 AS MaxCapacity, 
            @TotalMinutes AS TotalMinutesInShift,
            @SlotDuration AS SlotDurationMinutes,
            'Error: Duración de cita inválida.' AS StatusMessage;
        RETURN;
    END

    SET @MaxCapacity = FLOOR(@TotalMinutes / @SlotDuration);

    SELECT
        @MaxCapacity AS MaxCapacity,
        @TotalMinutes AS TotalMinutesInShift,
        @SlotDuration AS SlotDurationMinutes,
        'Cálculo exitoso' AS StatusMessage;
END
GO

